### ISSUE TITLE
Can't open an important LINK 404 NOT FOUND

### ISSUE THREAD

**Issue by angecas** [academictorrents/academictorrents-docs#22]
https://academictorrents.com/details/5a447ff50062194bd58dd11c0fedead59e6d873c  I'm looking at this page and I was investigating in what kind of investigation this dataset was used. But the link that gave access to this information is unavailable

https://wiki.cancerimagingarchive.net/display/Public/SPIE-AAPM-NCI+PROSTATEx+Challenges

the above link gives 404 not found error

**Comment by ieee8023** [comment]
The link seems to work now.
