### ISSUE TITLE
VGG Face2 dataset, redistribution of copyrighted material

### ISSUE THREAD

**Issue by adamhrv** [academictorrents/academictorrents-docs#24]
I ran an OCR analysis on the VGG Face 2 dataset (https://academictorrents.com/details/535113b8395832f09121bc53ac85d7bc8ef6fa5b) and found 13,957 images watermarked with a Getty Images copyright. Is it legal to redistribute copyright images from Getty on Academic Torrents?

There are a similar number of images with watermarks from other stock photo agencies including Alamy and Shutterstock. These numbers only quantify the verifiable watermarked images. The actual number of copyrighted images is likely significantly higher, if not comprising the entire dataset as the images were scraped from search engines w/o any indication of licenses. It's notable that VGG has removed the VGG Face 2 dataset from their own site (http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/, 404) citing pending legal concerns from their University's legal department. 

Below is an example on `n000001/0046_01.jpg` from the `test` partition

Should redistribution of this and other copyrighted material be permitted on Academic Torrents?

![vggface2_example](https://user-images.githubusercontent.com/199849/122901105-85765780-d34d-11eb-9f91-5e3beab6da7e.png)

**Comment by ieee8023** [comment]
Hello,

This is a forum for support when using the Academic Torrents platform. 

For any legal concerns please see https://academictorrents.com/docs/about.html#legal

**Comment by adamhrv** [comment]
Please check your email "contact@academictorrents.com". It's been down for at least 2 weeks.

GitHub seems to be the only way to establish contact about issues regarding your unauthorized distribution of copyrighted material.
