### ISSUE TITLE
what does "visible" mean in the torrent technical page?

### ISSUE THREAD

**Issue by carandraug** [academictorrents/academictorrents-docs#35]
In the technical page of some torrents, there is a field named "visible". Not al torrents have this field, but the ones that have seem to always have the value "no (dead)". Looks like this:

![academic-torrent-visible](https://user-images.githubusercontent.com/916140/199235045-effb7b02-319d-42e1-aab2-419db53708fa.png)

What does this mean?

**Comment by ieee8023** [comment]
That is an internal flag to detect files with no seeds. It is just used to display a warning to people that uploaded torrents that their torrents are not able to be downloaded. It looks like this:

<img width="1003" alt="Screen Shot 2022-11-01 at 12 13 05 PM" src="https://user-images.githubusercontent.com/446367/199318569-7ab5d8da-0d23-45e4-95f5-e0a1eca75e01.png">

**Comment by carandraug** [comment]
I don't thinks that's the same as the one I've asked asked. The one I've asked about is:

* visible to everyone (even to anonymous users)
* appears on the table of technical details
* appears on torrents that do have seeds

Here's one such torrent https://academictorrents.com/details/34f2197d360ac8453b33f50d09e452d504d30cbb/tech

**Comment by ieee8023** [comment]
Ah sorry I though those were both based on the same information. The visible flag is not used anymore. It was used filter the search to torrents which had seeders available. But it is not filtered like that anymore. It should be removed.

**Comment by carandraug** [comment]
I see. Is the code for the site at `academictorrents.com` hosted somewhere? I couldn't find a repo for it.

**Comment by ieee8023** [comment]
It is private for security reasons.

**Comment by carandraug** [comment]
This seems to have already been fixed because it has disappeared from the torrent I previously linked. Or maybe it has not been fixed and it simply no longer applies to that specific torrent? Can I get access to the code for the academictorrents?

**Comment by ieee8023** [comment]
> This seems to have already been fixed because it has disappeared from the torrent I previously linked. 

Yes. It was removed. Thanks for bringing it to our attention before. It wasn't useful for users to see.

> Can I get access to the code for the academictorrents?

We are not opening up access to the source at this moment sorry.
