### ISSUE TITLE
Cloudflare fingerprinting scripts are completely unacceptable.

### ISSUE THREAD

**Issue by KOLANICH** [academictorrents/academictorrents-docs#37]
>Checking site security...

is also unacceptable, it is not the website is measured, but user's browser. The message with more correct meaning is

>Fingerprinting your browser, waiting for the decision of Cloudflare if we should discriminate against you, helping Cloudflare to discriminate against users of certain kinds of browsers

**Comment by ieee8023** [comment]
I'm not sure I understand what the issue is. Is the site not working for you? What is your browser? I believe if you are seeing the "Checking site security" message and it is not changing then there is some sort of proxy between you and the server, so in that case there is an issue with security.

**Comment by KOLANICH** [comment]
"What is your browser" - Mozilla Firefox [it has negligible `~3%` of market share](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers). JavaScript is disabled. `privacy.resistFingerprinting` is set to `true`.

![browsers market share in 2023](https://www.oberlo.com/media/1679306491-most-popular-browsers-in-2023.png)

>I believe if you are seeing the "Checking site security" message and it is not changing

There should be no such a message and no such a "check" at all! Of course, this message is expected to disappear ... for ordinary people who use Chromium-based browsers (65.76 + 4.28 + 2.59 + 2.26 = 74.89), which take almost no measures (compared to Firefox) to protect users, so they are not discriminated against. Of course, if users of Firefox are not welcome on websites (and on some websites, where Cloudflare fingerprinting is not integrated into website engine, but works by replacing webpages by Cloudflare itself, they see additional screens), ordinary people will use Chromium-based browsers instead just to stay out of trouble.

**Comment by ieee8023** [comment]
The site works in firefox. You need to enable JavaScript.

**Comment by KOLANICH** [comment]
>You need to enable JavaScript.

I don't.
