### ISSUE TITLE
Unable to download mjsynth dataset torrent.

### ISSUE THREAD

**Issue by alibulus** [academictorrents/academictorrents-docs#39]
It always stucks on 

Downloading • 80.4% • 8.6 GB / 11 GB • 11 peers • 0s remaining

It is same with the 12 peers or 10 peers. I tried it for 3 days. Please fix this issue, i need this dataset.

**Comment by ieee8023** [comment]
I just tested this torrent and it downloads successfully in 2 locations. Can you try a different network? Possibly there is some rate limiting on the network you are using. If not please share some logs with errors that are generated when you are downloading.

**Comment by alibulus** [comment]
> I just tested this torrent and it downloads successfully in 2 locations. Can you try a different network? Possibly there is some rate limiting on the network you are using. If not please share some logs with errors that are generated when you are downloading.

It worked with vpn, thank you very much.
