### ISSUE TITLE
educational or approved accounts

### ISSUE THREAD

**Issue by tjrsgbe** [academictorrents/academictorrents-docs#40]
Uploading is restricted to educational or approved accounts only. I have updated to my profile email an educational address (e.g. @ua.pt, @ipb.pt and @utad.eu) and tried other e-mail, how can I enable uploading of academic information?

**Comment by ieee8023** [comment]
ua.pt and ipb.pt are approved domains. Maybe you didn't confirm the domain change step? Do you want to email us your account details so I can look into it more? contact@academictorrents.com

**Comment by tjrsgbe** [comment]
Hi. How are you? Thank you, now it seems to work.

**Comment by ieee8023** [comment]
Glad to hear. Let us know if you have any other issues.
