### ISSUE TITLE
Signup was Successfull but No Confirmation Email was Recieved

### ISSUE THREAD

**Issue by CodingVoyagerPrincess** [academictorrents/academictorrents-docs#42]
Please help. I really need to access a database.

**Comment by ieee8023** [comment]
Did you try to sign up with a different email account? Some email services block our domain.

**Comment by CodingVoyagerPrincess** [comment]
> Did you try to sign up with a different email account? Some email services block our domain.

Thank you. I use gmail. It was in my spam.
